# A small stack which includes a mariadb-server and a phpmyadmin-instance

version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "ROOT_PASSWORD"
      MYSQL_DATABASE: "DB"
      MYSQL_USER: "USER"
      MYSQL_PASSWORD: "PASS"
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_USER: "USER"
      PMA_PASSWORD: "PASS"
    ports:
      - 8082:80
    links:
      - db
